# UNITS FOR MCNP
# CM-G-SHAKE
MICRON = 1.0e-4
MCNP_DENSITY_FACTOR = -1
MCNP_WT_FRAC_FACTOR = -1

# MEAN PARTICLE PARAMETERS ACCORDING TO SPEC
# PARTICLES USE SPEC PROPERTIES UNLESS OTHERWISE SPECIFIED
NOMINAL_PACKING_FRAC = 0.4  # amount of space taken up by fuel particles

BUFFER_THICKNESS = 100 * MICRON
BUFFER_DENSITY = 1.05
IPYC_THICKNESS = 40 * MICRON
IPYC_DENSITY = 1.9
SIC_THICKNESS = 35 * MICRON
SIC_DENSITY = 3.19
OPYC_THICKNESS = 40 * MICRON
OPYC_DENSITY = 1.9

# MCNP UNIVERSE, MATERIAL, AND CELL SELECTION
FIRST_PARTICLE_CELL = 10000
PARTICLE_CELL_INCREMENT = 10
FIRST_PARTICLE_UNIVERSE = 10000
PARTICLE_UNIVERSE_INCREMENT = 1
FIRST_CELL_UNIVERSE = 50000
CELL_UNIVERSE_INCREMENT = 1
FIRST_PARTICLE_SURFACE = 10000
PARTICLES_SURFACE_INCREMENT = 10
FIRST_MATERIAL_NUMBER = 1000
MATERIAL_INCREMENT = 1
FIRST_TRANSFORM_NUMBER = 100
TRANSFORM_INCREMENT = 1
